server:
  port: 9080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      producer: ex.producer.felipe-development
    routing-key:
      producer: rk.producer.felipe-development
    deadletter:
      producer: dl.producer.felipe-development
